# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_carro', models.CharField(max_length=50)),
                ('Modelo', models.CharField(max_length=24)),
                ('Costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='comida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_comida', models.CharField(max_length=50)),
                ('tipo_de_comida', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='pasatiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_pasatiempo', models.CharField(max_length=50)),
                ('Tiempo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_trabajo', models.CharField(max_length=50)),
                ('tipo_trabajo', models.CharField(max_length=24)),
                ('Salario', models.IntegerField()),
            ],
        ),
    ]
