# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cancion',
            fields=[
                ('idcancion', models.CharField(max_length=30)),
                ('nombrecancion', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('anodisco', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='disco',
            fields=[
                ('iddisco', models.CharField(max_length=30)),
                ('nombredisco', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nocanciones', models.IntegerField()),
                ('artista', models.CharField(max_length=30)),
                ('ano', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='disquera',
            fields=[
                ('iddisquera', models.CharField(max_length=70)),
                ('nombredisquera', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('nodiscos', models.IntegerField()),
                ('ceo', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('idmanager', models.CharField(max_length=30)),
                ('nombremanager', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechanacmanager', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='musico',
            fields=[
                ('idmusico', models.CharField(max_length=70)),
                ('nombremusico', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fechanacmusico', models.DateField()),
                ('nodiscosmusico', models.IntegerField()),
            ],
        ),
    ]
